export const constants = {
    performance: {
        displayedColumns: ['agentCode', 'proposalID', 'proposalSubStatus', 'clientID',
            'insuredName', 'businessType', 'policyStartDate', 'policyEndDate',
            'policyNumber', 'productName', 'policyVariant', 'planType', 'planVariant',
            'portability', 'netPremium', 'sumInsured', 'inwardedDate', 'issueDate', 'prDate', 'portPercent',
            'superPercent', 'cI_CS_PA_ASPCreditPercent', 'siCreditPercent',
            'weightedNetPremium'],
        customHeaders: [
            'Agent Code',
            'Proposal ID',
            'Proposal Substatus',
            'Client ID',
            'Insured Name',
            'Business Type',
            'Policy Start Date',
            'Policy End Date',
            'Policy Number',
            'Product Name',
            'Policy Variant',
            'Plan Type',
            'Plan Variant',
            'Portability',
            'Net Premium',
            'Sum Insured',
            'Inwarded Date',
            'Issue Date',
            'PR Date',
            'Port%',
            'Super%',
            'CI/CS/PA/ASP/Credit%',
            'SI Credit%',
            'Weighted Net Premium']
    },
}