server {
    listen 80;

    # Serve Angular app
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to authentication service
    location /api/auth/ {
         # This will capture everything after /api/auth/ and strip the /api/auth/ prefix
        rewrite ^/api/auth/(.*)$ /$1 break;

        # Forward the request to the backend on port 7253
        proxy_pass http://auth-service:8080/;

        # Preserve headers for the proxied request
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy API requests to renewal service
    location /api/renewal/ {
        proxy_pass http://localhost:7210;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy API requests to quote service
    location /api/quote/ {
        proxy_pass http://localhost:7188;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}


# one more thing to run backend and frontend properly and backend can give response correclty we need to puth folder in c drive of the system but in case of docker how can we do thi
