export const environment = {
  production: false,
  baseUrl: "https://usp.monocept.ai/",
  baseUrl1: "https://upuat.adityabirlahealth.com/",
  axisBaseUrl: "https://affinitycld-uat.adityabirlahealth.com/Axis_redirection_data_new/api",
  getRenewalList: "api/renewal/getrenewallist",
  getRenewalInfo: "api/renewal/renewalinfo",
  getTenureDetails: "api/renewal/getquoteforsingleproduct",
  sendRenewalWhatappsms: "api/renewal/sendrenewalwhatappsms",
  sendRenewalsms: "api/renewal/sendrenewalsms",
  sendRenewalEmail: "api/renewal/sendrenewalnotice",
  generatePaymentlink: "api/renewal/generatepaymentlink",
  updatenominee: "api/renewal/updatenominee",
  updateaddress: "api/renewal/updateaddress",
  updateBankDetails: "api/renewal/savebankdetails",
  getproductdetailsandfeatures: "api/renewal/getproductdetailsandfeatures",
  getSubquotes: "api/renewal/getsubquotes",
  updateMemberDetails: "api/renewal/UpdateMemberDetails",
  kycUpdate: "api/renewal/kycUpdate",
  updateNomineeDetail:"api/renewal/updateNomineeDetails",
  updateBankDetailApi:"api/renewal/updateBankDetails",
  getbasequote:"api/renewal/getbasequote",
  generatehalfqoute:"api/renewal/generatehalfqoute",
  sharekyclink: "api/quote/sharekyclink",
  skipkyclink: "api/quote/forcedkycupdate",
  getPaymentDetails: "api/yatra/getpaymentdetails",
  getDetailsForKyc: "api/quote/getkycdetails",
  fullQuote: "api/yatra/offlinePayment",
  cpRedirectionApi: "api/renewal/cp-redirection",
  sharePaymentLink: "api/yatra/sharepaymentlink",
  getkycURL: "api/quote/getkycURL",
  getLeadsListApi: "api/yatra/getLeadList",
  getActiveCampaignDetails: "api/yatra/getactivecampaignsdetails",
  saveLeadData: "api/yatra/createlead",
  exportLeads: "api/yatra/exportleadAll",
  exportLead: "api/yatra/exportlead",
  getLeadInfoByLeadNumber: "api/yatra/leadbyleadnumber?leadNumber=",
  getcampaignsdetails: "api/yatra/getcampaignsdetails",
  createbulklead: "api/yatra/createbulklead",
  viewaudittrail: "api/yatra/viewaudittrail?leadnumber=",
  referencestatus: "api/yatra/referencestatus",
  updatestatus: "api/yatra/updatestatus",
  getduplicateLead: "api/yatra/getduplicateLead",
  getPaymentStatus: "api/yatra/paymentstatus",
  getpaymentdetailsbypolicyno: "api/yatra/getpaymentdetailsbypolicyno",
  assineLead: "api/yatra/LeadAssigne",
  getMyReportingUsers: "api/yatra/getmyreportingusers",
  fetchActivityType: "api/yatra/fetchactivitytype",
  getProposalListApi: "api/yatra/getproposallist",
  getQuoteListApi: "/api/quote/getcartlist",
  getCustomerList: "api/yatra/getCustomerList",
  sendCustomerDetails: "/api/yatra/sharepolicykit",
  download: "api/yatra/downloadcustomer",
  addLeadNotes: "api/yatra/addnotes",
  getLeadNotes: "api/yatra/notelist?leadNumber=",
  addfeedback: "api/yatra/feedback",
  getClaimsList: "api/claims/getclaimlist",
  getCoverNames: "api/claims/GetMemberCovers",
  getProposalDetails: "api/claims/getproposaldetails?AgentCode",
  saveClaims: "api/claims/saveclaim",
  updateClaim: "api/claims/updateclaimdocument",
  uploadFiles: "api/claims/saveuploadfiledetails",
  getStates: "api/claims/getstatename",
  getCities: "api/claims/getcityname",
  getClaimHistory: "api/claims/getclaimhistory?policynumber",
  blackListedHospitals: "api/claims/blacklistedhospitals",
  getClaimsDetails: "api/claims/getclaimdetails",
  getHospitals: "api/claims/FetchHospitalDetails",
  getClaimStatus: "api/claims/getclaimstatus",
  getClaimStatusCounts: "api/claims/GetClaimStatusCountByAgentCode?agentCode",
  getMemberDetails: "api/claims/getpolicymembers",
  getClaimTracker: "api/claims/getclaimtracker",
  getUploadedFiles: "api/claims/getclaimsdocument",
  deleteFile: "api/claims/deleteclaimdocument",
  claimDownloadAll: "api/claims/claimdownload",
  saveEvent: "api/yatra/insertevent",
  getEvents: "api/yatra/eventlist",
  getEventLead: "api/yatra/eventlead",
  getEventProposal: "api/yatra/eventproposal",
  deleteEvent: "api/yatra/deleteevent",
  eventListById:"api/yatra/eventlistbyid",
  getBirthdays: "api/yatra/getcustomersbirthdays",
  sendIndividualWishes: "api/yatra/sendwishes",
  sendWishesToAll: "api/yatra/sendwishesall",
  getPerformanceDetails: "api/yatra/getPerformanceDetails",
  getPerformanceDetailedViewList: "api/yatra/getPerformanceDetailedViewList",
  getPerformanceDetailedViewLatestCount: "api/yatra/getPerformanceDetailedViewLatestCount",
  uploadAgencyPerformance: "api/yatra/UploadAgencyPerformance",
  partnerlogin: "api/auth/login",
  resetPassword: "api/auth/resetpassword",
  validateadfstoken: "api/auth/validateadfstoken?Idtoken=",
  validatecyberarktoken: "api/auth/validatecyberarktoken?Idtoken=",
  getContactDetailsByAgentCode: "api/auth/getcontactdetailsbyagentcode",
  sendotp: "api/auth/sendotp",
  validateotp: "api/auth/validateotp",
  endorsementdetails: "api/claims/endorsementdetails",
  getactivepolicynumbers: "api/claims/getactivepolicynumbers",
  getPolicyMembers: "api/claims/getpolicymembers",
  endorsementfileuploadtoomnidocs: "api/claims/endorsementfileuploadtoomnidocs",
  endorsementcreaterequest: "api/claims/endorsementcreaterequest",
  endorsementGetOTP: "api/claims/endorsementsendotp",
  endorsementValidateOTP: "api/claims/endorsementvalidateotp",
  getpolicyinfodetails: "api/claims/getpolicyinfodetails",
  endorsementCaseDetails: "api/claims/getcasedetailsbycaseid",
  getEndorsementStatus: "api/claims/getstatusbycaseid",
  endorsementDownloadAll: "api/claims/endorsementdownload",
  agentCartDetails: "api/quote/getagentcartdetails",
  insertOrUpdateAgentCartDetails: "api/quote/insertorupdateagentcartdetails",
  deleteagentcartitems: "api/quote/deleteagentcartitems",
  productList: "api/yatra/getproductlist",
  pinCodeDetails: "api/yatra/getpincodeandSIdetails",
  proposalNumber: "api/yatra/getproposalnumber",
  formSequence: "api/yatra/getformsequence",
  getForm: "api/yatra/getform",
  getNatureOfDuty: "api/yatra/getnatureofduty",
  getOccupation: "api/yatra/getoccupation",
  getProposerOccupation: "api/yatra/getproposeroccupation",
  ShareProposalSummary:"api/yatra/shareproposal",
  downloadQuote : "api/yatra/downloadquote",
  getNomineeRelationShip: "api/yatra/getnomineerelationship",
  getAllBankDetails: "api/yatra/getbanknames",
  getBankCity: "api/yatra/getbankcitydetails",
  getBranchDetails: "api/yatra/getbankbranchdetails",
  getProposerRelationships: "api/yatra/getproposerrelationships",
  insertOrUpdateFormData: "api/yatra/insertorupdateformdata",
  insertOrUpdateJourneyDetails: "api/yatra/insertorupdatejourneydetails",
  getHalfQuote: "api/yatra/gethalfquote",
  getFullQuote: "api/yatra/getfullquote",
  getProductDetailsAndFeatures: "api/yatra/getproductdetailsandfeatures",
  getSingleProductQuote: "api/quote/getquoteforsingleproduct",
  getKycDetails: "api/quote/getkycdetails",
  getquotefortopsellingproducts: "api/quote/getquotefortopsellingproducts",
  getPolicyNumberDetails: "api/yatra/getcustomerpolicydetailsviapolicynum",
  profileDetails: "api/auth/GetAgentProfileDetails",
  escalationMatrixDetails: "api/yatra/GetEscalationMatrixDetails",
  updateagentlanguagepreference: "api/yatra/updateagentlanguagepreference",
  fetchPolicyDetailsFromFile: "api/yatra/getcustomerpolicydetailsfrompolicydocument",
  justPayRedirection: "api/yatra/Payment/JuspayOrder",
  insertfullquotejson: "api/yatra/insertfullquotejson",
  getfullquoteviaofflinepayment: "api/yatra/getfullquoteviaofflinepayment",
  paymentGateway: "api/yatra/Payment/JuspayOrder",
  getRelations: "api/rug/GetProposerRelations",
  getProductCombination: "api/rug/GetProductCombination",
  getBBProposalDetails: "/BranchBanking/GetBBProposalDetailsV2",
  getSumInsuredDetails: "api/rug/GetSumInsuredList",
  getBBPolicyInfoByLeadId: "api/rug/GetBBPolicyInfoByLeadId",
  getPremiumDetaiks: "/Product/GetPremium",
  getRUGPremium: "api/rug/GetPremium",
  getFamilyConstruct: "api/rug/GetFamilyConstructByProductCode",
  bbAxisRedirection: "api/v1/RedirectAxisBranchBankingRequest",
  saveBBCommonDraft: "api/rug/SaveBBCommonDraft",
  getLeadStatusCount: "GetLeadStatusCount",
  getProposalStatusCount: "GetProposalStatusCount",
  getRenewalStatusCount: "GetRenewalStatusCount",
  getNotification: "api/quote/notificationlist?agentcode=",
  markAllReadNotifications: "api/quote/readall?agentCode=",
  markNotification: "api/quote/notificationbyid?id=",
  uploadDocument: "api/yatra/uploaddocument",
  searchDeytailsByPrfix: "api/quote/SearchLeadPolicyClaim",
  fetchPermoranceDetails: "api/quote/GetWidgetData",
  fetchPersistencyPercentage: "api/quote/GetPersistencyPercentage",
  GetDueRenewals: "api/quote/GetDueRenewals",
  getBBOTP: "api/rug/GetBBOTP",
  getValidateBbOtp: "api/rug/ValidateBBOTP",
  getBankDetailsViaIFSC: "api/yatra/getbankdetailsviaifsccode",
  searchDocument: "api/yatra/searchdocument",
  downloadDocument: "api/yatra/download",
  getCustomerBasicDetails: "api/yatra/GetPolicyBasicDetails",
  getCustomerProductDetails: "api/yatra/customerproducts?PolicyNumber",
  getCustomerInsuredDetails: "api/yatra/customermember?PolicyNumber",
  getCustomerClaimDetails: "api/yatra/getclaimdetails",
  getCustomerEndorsementDetails: "api/yatra/customerservice?PolicyNumber",
  fetchCommmission: "api/renewal/DocumentSearch",
  downloadCommmissionStatement: "api/renewal/DocumentDownload",
  getquoterelationsviapolicytype: "api/quote/getquoterelationsviapolicytype",
  getTopProducts: "api/quote/GetTopSellingProduct",
  updateAgentAllFormData: "api/rug/UpdateAgentAllFormData",
  getd2cPolicyInfoByLeadId: "api/rug/GetD2CPolicyInfoByLeadId",
  fetchDashboardPreferences: "api/quote/GetDashboardPreference",
  SubmitDashboardPreferences: "api/quote/InsertDashboardPreference",
  getBankDetailsByIFSC:"api/rug/GetBankDetailsByIfsc",
  fetchPennydropverification:"api/yatra/pennydropverification",
  downloadQuotePDf : "api/yatra/GeneratePDF",
  seriveRequest : "api/auth/GenerateTokenAndSsoUrl",
  sendOTP : "api/yatra/declarationotp",
  verifyOTP : "api/yatra/declarationvalidateotp",
  sendEmailLink : "api/yatra/emaillink",
  createUpdateAv:"api/v1/CreateUpdateAV",
  staticForm : "api/yatra/getstaticforms",
  getallAv:"api/v1/GetAllAVs?pageNo=1&noOfRow=50",
  getAllManageLob:"api/v1/GetAllManageLOB",
  getkycstatus : "api/quote/getkycstatusviaproposalnum",
  fetchPennyVerificationByOCR: "api/yatra/pennydropverificationviaocr",
  getInsertproposerdocumentid: "api/yatra/insertproposerdocumentid",
  sCreateLead: "api/v1/SaveLeadDetails",
  getAllManageLOB: "api/v1/GetAllManageLOB",
  getPincodeDetails:"api/rug/GetPincodeDetails",
  tsCreateLead: "api/v1/SaveLeadDetails",
  getAllDispositions: "api/rug/getAllDisposition?appName=TELESALES",
  getAllSubDispositions:'api/rug/GetAllSubDisposition',
  saveTSCommonDraft:"api/rug/SaveTSCommonDraft",
  postTSHalfQuote:"api/v1/PostHalfQuote",
  getTSPolicyInfoByLeadId:"api/v1/GetTSPolicyInfoByLeadId",
  bbHalfQuote: "api/rug/HalfQuote",
  getAllLocationAndvendors:"api/v1/GetAllVendorsAndLocations",
  updateAv:"api/v1/CreateUpdateAV",
  deleteAV:"api/v1/DeleteAV",
  bulkUpload:"api/v1/BulkUpload",
  GetLeads: "api/rug/GetLeads",
  getMasterData:"api/rug/GetMasterDetails",
  getBaseCaller:"api/rug/GetAllBaseCallers",
  getpaymentdetailsbyproposalno: "api/yatra/getpaymentdetailsbyproposalno",
  getLeads:"api/rug/GetLeads",
  assignToAv:"api/rug/AssignToAV",
  getAllAudit:"api/rug/GetAllAudit",
  d2cAxisRedirection: "api/v1/",
  assignBackToDo:"api/rug/AssignBackToDo",
  verifylink:"api/yatra/verifylink",
  confirmproposer:"api/yatra/confirmproposer",
  extractMastarData:"api/rug/ExtractMasterData",
  getTSPolicyInfoLeadId:"api/rug/GetTSPolicyInfoByLeadId",
  pinCodeDetailsQuote: "api/yatra/getpincodedetails",
  getBaseCallerDetails: "api/rug/GetBaseCallerDetails",
  DeleteBaseCaller:"api/rug/DeleteBaseCaller",
  CreateUpdateBaseCaller:"api/rug/CreateUpdateBaseCaller",
  getforminfobyproposalNum:"api/yatra/getforminfobyproposalNum",
  insertoptionalcoversjson:"api/yatra/insertoptionalcoversjson",
  createLob:"api/rug/CreateManageLob",
  getsuminsuredlist:"api/yatra/getactivesecuresidetails",
  getAllAvsByLocation:"api/rug/GetAllAVsByLocation",
  checkGroupRenewalData:"api/rug/CheckGroupRenewalData",  
  getAllDispositionsRenewal: "api/rug/getAllDisposition?appName=RENEWAL",
  SaveRenewalProposalData: "api/rug/SaveRenewalProposalData",
  getRetailRenewalRedirectUrl: "api/rug/GetRetailRenewalRedirectUrl",
  sendLinkToCustomer: "api/rug/SendLinkToCustomer",
  sendRetailLinkToCustomer: "api/rug/SendRetailLinkToCustomer",
  getRetailRenewalPhaseTwoLeads: "api/rug/GetRetailRenewalPhaseTwoLeads",
  getRenewalPolicyData: "api/rug/GetRenewalPolicyData",
  getGroupRenewalPhaseTwoLeads: "api/rug/GetGroupRenewalPhaseTwoLeads",
  getParentCodeViaAgentId:"api/yatra/getflsagents",
  sendOtpHdfc:"api/rug/generateotp",
  validateHdfcOTP:"api/rug/validateotp",
  sendCommunication:"api/rug/send-communication",
  generateProposal:"api/rug/generateproposal",
  getEmployeeDetails:"api/rug/GetEMployeeDetails",
  createBataleads:"api/rug/SaveLeadDetailshdfc",
  gethdfcProductDetails:"api/rug/GetProductCombination"
};
