export const environment = {
    baseUrl: "https://usp.monocept.ai/",
    baseUrl1: "https://upuat.adityabirlahealth.com/",
    axisBaseUrl: "https://affinitycld-uat.adityabirlahealth.com/Axis_redirection_data_new/api",
    getRenewalList: "api/renewal/getrenewallist",
    getRenewalInfo: "api/renewal/renewalinfo",
    getTenureDetails: "api/renewal/getquoteforsingleproduct",
    sendRenewalWhatappsms: "api/renewal/sendrenewalwhatappsms",
    sendRenewalsms: "api/renewal/sendrenewalsms",
    sendRenewalEmail: "api/renewal/sendrenewalnotice",
    generatePaymentlink: "api/renewal/generatepaymentlink",
    updatenominee: "api/renewal/updatenominee",
    updateaddress: "api/renewal/updateaddress",
    updateBankDetails: "api/renewal/savebankdetails",
    getproductdetailsandfeatures: "api/renewal/getproductdetailsandfeatures",
    getSubquotes: "api/renewal/getsubquotes",
    updateMemberDetails: "api/renewal/UpdateMemberDetails",
    kycUpdate: "api/renewal/kycUpdate",
    fullQuote: "api/yatra/offlinePayment",
    getkycURL: "api/quote/getkycURL",
    getLeadsListApi: "api/yatra/getleaddetailslist",
    getActiveCampaignDetails: "api/yatra/getactivecampaignsdetails",
    saveLeadData: "api/yatra/createlead",
    getLeadInfoByLeadNumber: "api/yatra/leadbyleadnumber?leadNumber=",
    getcampaignsdetails: "api/yatra/getcampaignsdetails",
    createbulklead: "api/yatra/createbulklead",
    viewaudittrail: "api/yatra/viewaudittrail?leadnumber=",
    referencestatus: "api/yatra/referencestatus",
    updatestatus: "api/yatra/updatestatus",
    getduplicateLead: "api/yatra/getduplicateLead",
    getPaymentStatus: "api/yatra/paymentstatus",
    assineLead: "api/yatra/LeadAssigne",
    getMyReportingUsers: "api/yatra/getmyreportingusers",
    fetchActivityType: "api/yatra/fetchactivitytype",
    getProposalListApi: "api/yatra/getproposallist",
    getCustomerList: "api/yatra/getCustomerList",
    sendCustomerDetails: "/api/yatra/sendcustomerdetails",
    download: "api/yatra/downloadcustomer",
    addLeadNotes: "api/yatra/addnotes",
    getLeadNotes: "api/yatra/notelist?leadNumber=",
    addfeedback: "api/yatra/feedback",
    getClaimsList: "api/claims/getclaimlist",
    getCoverNames: "api/claims/GetMemberCovers",
    getProposalDetails: "api/claims/getproposaldetails?AgentCode",
    saveClaims: "api/claims/saveclaim",
    updateClaim: "api/claims/updateclaimdocument",
    uploadFiles: "api/claims/saveuploadfiledetails",
    getStates: "api/claims/getstatename",
    getCities: "api/claims/getcityname",
    getClaimHistory: "api/claims/getclaimhistory?policynumber",
    blackListedHospitals: "api/claims/blacklistedhospitals",
    getClaimsDetails: "api/claims/getclaimdetails",
    getHospitals: "api/claims/FetchHospitalDetails",
    getClaimStatus: "api/claims/getclaimstatus",
    getClaimStatusCounts:"api/claims/GetClaimStatusCountByAgentCode?agentCode",
    getMemberDetails:"api/claims/getpolicymembers",
    getClaimTracker: "api/claims/getclaimtracker",
    getUploadedFiles: "api/claims/getclaimsdocument",
    deleteFile: "api/claims/deleteclaimdocument",
    saveEvent: "api/yatra/insertevent",
    getEvents: "api/yatra/eventlist",
    getBirthdays:"api/yatra/getcustomersbirthdays",
    sendIndividualWishes:"api/yatra/sendwishes",
    sendWishesToAll:"api/yatra/sendwishesall",
    getPerformanceDetails: "api/yatra/getPerformanceDetails",
    getPerformanceDetailedViewList: "api/yatra/getPerformanceDetailedViewList",
    getPerformanceDetailedViewLatestCount: "api/yatra/getPerformanceDetailedViewLatestCount",
    uploadAgencyPerformance: "api/yatra/UploadAgencyPerformance",
    partnerlogin: "api/auth/login",
    resetPassword: "api/auth/resetpassword",
    validateadfstoken: "api/auth/validateadfstoken?Idtoken=",
    validatecyberarktoken: "api/auth/validatecyberarktoken?Idtoken=",
    getContactDetailsByAgentCode: "api/auth/getcontactdetailsbyagentcode",
    sendotp: "api/auth/sendotp",
    validateotp: "api/auth/validateotp",
    endorsementdetails: "api/claims/endorsementdetails",
    getactivepolicynumbers: "api/claims/getactivepolicynumbers",
    getPolicyMembers: "api/claims/getpolicymembers",
    endorsementfileuploadtoomnidocs: "api/claims/endorsementfileuploadtoomnidocs",
    endorsementcreaterequest: "api/claims/endorsementcreaterequest",
    endorsementGetOTP: "api/claims/endorsementsendotp",
    endorsementValidateOTP: "api/claims/endorsementvalidateotp",
    getpolicyinfodetails: "api/claims/getpolicyinfodetails",
    endorsementCaseDetails: "api/claims/getcasedetailsbycaseid",
    agentCartDetails: "api/quote/getagentcartdetails",
    insertOrUpdateAgentCartDetails: "api/quote/insertorupdateagentcartdetails",
    deleteagentcartitems: "api/quote/deleteagentcartitems",
    productList: "api/yatra/getproductlist",
    pinCodeDetails: "api/yatra/getpincodedetails",
    proposalNumber: "api/yatra/getproposalnumber",
    formSequence: "api/yatra/getformsequence",
    getForm: "api/yatra/getform",
    getNatureOfDuty: "api/yatra/getnatureofduty",
    getOccupation: "api/yatra/getoccupation",
    getProposerOccupation: "api/yatra/getproposeroccupation",
    getNomineeRelationShip: "api/yatra/getnomineerelationship",
    getAllBankDetails: "api/yatra/getbanknames",
    getBankCity: "api/yatra/getbankcitydetails",
    getBranchDetails: "api/yatra/getbankbranchdetails",
    getProposerRelationships: "api/yatra/getproposerrelationships",
    insertOrUpdateFormData: "api/yatra/insertorupdateformdata",
    insertOrUpdateJourneyDetails: "api/yatra/insertorupdatejourneydetails",
    getHalfQuote: "api/yatra/gethalfquote",
    getFullQuote: "api/yatra/getfullquote",
    getProductDetailsAndFeatures: "api/yatra/getproductdetailsandfeatures",
    getSingleProductQuote: "api/quote/getquoteforsingleproduct",
    getKycDetails: "api/quote/getkycdetails",
    getquotefortopsellingproducts: "api/quote/getquotefortopsellingproducts",
    getPolicyNumberDetails: "api/yatra/getcustomerpolicydetailsviapolicynum",
    profileDetails: "api/auth/GetAgentProfileDetails",
    escalationMatrixDetails:"api/yatra/GetEscalationMatrixDetails",
    fetchPolicyDetailsFromFile: "api/yatra/getcustomerpolicydetailsfrompolicydocument",
    justPayRedirection: "api/yatra/Payment/JuspayOrder",
    insertfullquotejson: "api/yatra/insertfullquotejson",
    getfullquoteviaofflinepayment: "api/yatra/getfullquoteviaofflinepayment",
    paymentGateway: "api/yatra/Payment/JuspayOrder",
    getRelations: "api/rug/GetProposerRelations",
    getProductCombination: "api/rug/GetProductCombination",
    getBBProposalDetails: "/BranchBanking/GetBBProposalDetailsV2",
    getSumInsuredDetails: "api/rug/GetSumInsuredList",
    getBBPolicyInfoByLeadId: "api/v1/GetBBPolicyInfoByLeadId",
    getPremiumDetaiks: "/Product/GetPremium",
    getRUGPremium: "api/rug/GetPremium",
    getFamilyConstruct: "api/rug/GetFamilyConstructByProductCode",
    saveBBCommonDraft: "api/v1/SaveBBCommonDraft",
    getLeadStatusCount: "GetLeadStatusCount",
    getProposalStatusCount: "GetProposalStatusCount",
    getRenewalStatusCount: "GetRenewalStatusCount",
    getNotification: "api/quote/notificationlist?agentcode=",
    markAllReadNotifications: "api/quote/readall?agentCode=",
    markNotification: "api/quote/notificationbyid?id=",
    uploadDocument: "api/yatra/uploaddocument",
    searchDeytailsByPrfix:"api/quote/SearchLeadPolicyClaim",
    fetchPermoranceDetails:"api/quote/GetWidgetData",
    fetchPersistencyPercentage:"api/quote/GetPersistencyPercentage",
    GetDueRenewals:"api/quote/GetDueRenewals",
    getBBOTP:"api/v1/GetBBOTP",
    getValidateBbOtp:"api/v1/ValidateBBOTP",
    getBankDetailsViaIFSC:"api/yatra/getbankdetailsviaifsccode",
    searchDocument: "api/yatra/searchdocument",
    downloadDocument:"api/yatra/download",
    getCustomerBasicDetails:"api/yatra/GetPolicyBasicDetails",
    getCustomerProductDetails:"api/yatra/customerproducts?PolicyNumber",
    getCustomerInsuredDetails:"api/yatra/customermember?PolicyNumber",
    getCustomerClaimDetails:"api/yatra/getclaimdetails",
    getCustomerEndorsementDetails:"api/yatra/customerservice?PolicyNumber",
    fetchCommmission:"api/renewal/DocumentSearch",
    downloadCommmissionStatement:"api/renewal/DocumentDownload"
  }