export class CreateLead {
    AgentCode!: string;
    firstname!: string;
    lastname!: string;
    middlename!: string;
    mobilenumber!: string;
    PhoneNumber!: string;
    emailid!: string;
    dob!: Date | string;
    age!: string;
    isWhatsapp!: boolean;
    gender!: string;
    maritalStatus!: string;
    numberOfKids!: Number;
    occupation!: string;
    education!: string;
    leadType!: string;
    leadVintage!: string;
    source!: string;
    subSource!: string;
    address1!: string;
    address2!: string;
    address3!: string;
    city!: string;
    state!: string;
    pincode!: string;
    interestedProductName!: string;
    planType!: string;
    policyEndDate!: Date;
    sumInsured!: string;
    premium!: string;
    duePremiun!: string;
    familyConstruct!: string;
    policyType!: string;
    policyNumber!: string;
    campaignname!: string;
    campaignnumber!: string;
    leadnumber!: string;
    leadAssignee!: string;
    isUpdate!: number;
    additionalInformation!: string;
    proposalNumber!:string;
    zone!:string;
    leadPriority!:string;

}