name: Build and Deploy Angular App to Azure VM

on:
  # push:
  #   branches:
       - RV_abhi_frontend_deploy
      # - Dev
      # - release
   workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Deployment environment'
  #       required: true
  #       default: 'abhi_dev'
  #       type: choice
  #       options:
  #         - abhi_dev
  #         - abhi_uat
  #         - abhi_prod

env:
  SONAR_PROJECT_KEY: "frontend-sonar-project"
  DEPLOY_BASE_DIR: "C:/ABHI_DATA/abhi_deployments/frontend_deployments"
  WEB_ROOT: "C:/USP/ABHI_DEPLOY"
  APP_POOL_NAME: "ABHIDEPLOY"
  SITE_NAME: "ABHIUSP"
  BINDING_HOST: "usp.monocept.ai"
  PORT: 8443

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.3'

    
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # - name: Print working directory and list its contents
    #   run: |
    #     echo "Current working directory is:"
    #     pwd  # Print the current working directory
    #     echo "Listing the contents of the current directory:"
    #     ls -la  # List the contents of the current working directory

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps

    - name: Clean previous build artifacts
      run: |
        rm -rf ./dist/*
      
    - name: Build the project
      run: |
        npm run build --prod

    # - name: List Build Artifacts
    #   run: ls -la ./dist/

    # - name: List contents in the current directory
    #   run: |
    #     pwd
    #     ls -la 
    #     ls -la MozartUI-Dev
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: angular-artifacts
        path: ./dist/*

    # - name: Debug:List files after downloading artifacts
    #   run: ls -l ./dist/

    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@v3.0.0
    #   with:
    #     projectBaseDir: .
    #     args: |
    #       -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
    #       -Dsonar.sources=./src
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # - name: Check SonarQube Quality Gate
    #   run: |
    #     status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
    #       "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
    #       | jq -r .projectStatus.status)
    #     echo "Quality Gate status: $status"
    #     if [ "$status" != "OK" ]; then
    #       echo "Quality Gate failed: $status"
    #       exit 1
    #     fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # environment: 
    #   name: ${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
        token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Set up SSH key
    #   run: |
    #       mkdir -p ~/.ssh
    #       case "${{ matrix.environment }}" in
    #         dev)
    #           echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #           ;;
    #         uat)
    #           echo "${{ secrets.UAT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #           ;;
    #         prod)
    #           echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #           ;;
    #         *)
    #           echo "Unknown environment: ${{ matrix.environment }}"
    #           exit 1
    #           ;;
    #       esac
    #       chmod 600 ~/.ssh/id_rsa

    #   - name: Configure SSH
    #     run: |
    #       echo "Host *" > ~/.ssh/config
    #       echo "    StrictHostKeyChecking no" >> ~/.ssh/config

    #   - name: Verify SSH connection
    #     run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Connected successfully to ${{ matrix.environment }} server'"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add VM to known hosts
      # run: |
        # mkdir -p ~/.ssh   
        # ssh-keyscan -v -H ${{ secrets.SSH_HOST }} > ssh_keyscan_output.log 2>&1 || { 
        # echo "ssh-keyscan failed. Details:"; 
        # cat ssh_keyscan_output.log; 
        # exit 1; 
        # }  
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      #run: ssh-keyscan -v -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>&1 || { echo 'ssh-keyscan failed'; exit 1; }

      #Generate the single version at the workflow level
    - name: Generate Deployment Version
      id: version
      run: |
        # Generate version using current date and time (IST)
        #CURRENT_DATE=$(date -d 'TZ="Asia/Kolkata" now' +"%Y%m%d-%H%M%S")
        CURRENT_DATE=$(TZ="Asia/Kolkata" date +"%Y%m%d-%H%M%S")
        TAGGED_VERSION="v${CURRENT_DATE}"
        echo "Deployment version: $TAGGED_VERSION"
        # Set the version as an output
        echo "::set-output name=version::$TAGGED_VERSION"
        # Also export it as an environment variable for other steps
        echo "TAGGED_VERSION=$TAGGED_VERSION" >> $GITHUB_ENV
  
    # - name: Debug:Show generated version
    #   run: |
    #     echo "Generated version: $TAGGED_VERSION"
  
    - name: Create deployment directory on VM with version
      run: |
        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "\$DeployDir = '${{ env.DEPLOY_BASE_DIR }}\\$TAGGED_VERSION'; try { if (-Not (Test-Path -Path \$DeployDir)) { Write-Output \"Creating deployment directory: \$DeployDir\"; New-Item -Path \$DeployDir -ItemType Directory; } else { Write-Output \"Deployment directory already exists: \$DeployDir\"; } } catch { Write-Output \"Error while creating deployment directory: \$DeployDir\"; Write-Output \$_.Exception.Message; exit 1; }"

    - name: Manage Previous Deployments (Keep Last 3)
      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"\$deploymentDir = '${{ env.DEPLOY_BASE_DIR }}'; \$deployments = Get-ChildItem -Path \$deploymentDir | Sort-Object LastWriteTime -Descending; if (\$deployments.Count -gt 3) { \$deployments | Select-Object -Skip 3 | Remove-Item -Recurse -Force }\""
    
    - name: Create directory for artifacts
      run: mkdir -p ./my-artifacts
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: angular-artifacts
        path: ./my-artifacts
    
    # - name: Debug:List files after downloading artifacts
    #   run: ls -l ./my-artifacts

    - name: Upload artifact to VM with versioning
      run: scp -i ~/.ssh/id_rsa -P 22 -r ./my-artifacts/angular-dev/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_BASE_DIR/$TAGGED_VERSION/
  
    - name: Upload deploy.ps1 to VM
      run: |
        scp -i ~/.ssh/id_rsa -P 22 ./scripts/frontend_new_deploy.ps1 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.DEPLOY_BASE_DIR}}/frontend_new_deploy.ps1
    
    - name: Execute frontend_deploy.ps1 script on VM
      run: |
        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -ExecutionPolicy Bypass -File ${{env.DEPLOY_BASE_DIR}}/frontend_new_deploy.ps1 -AppPoolName ${{ env.APP_POOL_NAME }} -SiteName ${{ env.SITE_NAME }} -WebRoot ${{ env.WEB_ROOT }} -DeployBaseDir ${{ env.DEPLOY_BASE_DIR }} -TaggedVersion ${{ env.TAGGED_VERSION }} -Port ${{env.PORT}} -BindingHost ${{env.BINDING_HOST}} -PfxPass ${{ secrets.SSL_CERT_PASSWORD }}"

    - name: Set environment variable based on branch
      run: |
        branch_name="${GITHUB_REF#refs/heads/}" # Strip out 'refs/heads/' from branch name
        environment=${branch_name}
        if [ "$environment" == "main" ]; then
          environment="prod"
        fi
        echo "ENVIRONMENT=$environment" >> $GITHUB_ENV
        echo "Environment is set to $environment"

    - name: Tag the commit
      if: ${{ success() }}  # Only tag if the workflow is successful
      run: |
        TAG="$ENVIRONMENT-$TAGGED_VERSION"
        echo "Tag: $TAG"  # Debugging the tag value
        git tag $TAG
        git push origin $TAG
    